name: Android CI

on:
  push:
    branches:
      - master
      - dev/huy
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          cmdline-tools-version: '8.0'

      # Grant execute permissions to gradlew
      - name: Grant execute permissions to gradlew
        run: chmod +x ./gradlew

      # Check ADB Installation
      - name: Check ADB Installation
        run: adb version

      # Start Android Emulator
      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Pixel_4
          cores: 2
          ram-size: 2048M
          sdcard-path-or-size: 512M
          emulator-options: "-no-snapshot -no-audio -no-window -no-accel"
          emulator-boot-timeout: 1200
          disable-linux-hw-accel: true
          avd-name: test
          force-avd-creation: true

      # Wait for Emulator to Boot
      - name: Wait for Emulator to Boot
        run: adb wait-for-device shell getprop sys.boot_completed | grep -m 1 '1'

      # Build and Test
      - name: Run Unit and UI Tests
        run: ./gradlew testDebugUnitTest connectedDebugAndroidTest

      # Terminate Emulator
      - name: Terminate Emulator
        run: adb emu kill
